# Site settings
title: Portfolio
description: Portfolio for projects url
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ishita-17.github.io" # the base hostname & protocol for your site

# User settings
username: Ishita Sarraf
user_description: Computer Science and Statistics 
user_title: Undergraduate Student
email: sarrafis@grinnell.edu
github_username:  ishita-17

exclude: ['package.json', 'src' , 'node_modules']
